Added chip component
SchweizerischeBundesbahnen/design_system_flutter pull request #72
Opened 2023-06-28 07:59 UTC by rawi-coding

Added chip component: https://digital.sbb.ch/de/design-system/mobile/components/chip/

2023-07-26 15:48 UTC, VanHoangTran requested changes
Looks pretty good so far. Needs some changes though ;-)

2023-07-26 15:48 UTC, VanHoangTran commented on lib/src/chip/sbb_chip.dart
> +        decoration: BoxDecoration(
StadiumBorder scales with bigger font sizes:
```dart
decoration: ShapeDecoration(
  shape: StadiumBorder(
    color: _disabled ? style.disabledBorderColor! : style.borderColor!,
  ),
),
```

2023-07-26 15:48 UTC, VanHoangTran commented on lib/src/chip/sbb_chip.dart
> +      margin: EdgeInsets.all(4.0).copyWith(left: 0),
`left: 0` results in an asymmetric InkWell ripple effect.
Suggestion: Keep left margin of 4 here and subtract 4 from label right padding.

2023-07-26 15:48 UTC, VanHoangTran commented on lib/src/theme/styles/src/sbb_chip_style.dart
> +  final Color? unselectButtonColor;
Missing text color for disabled state. I would also add text color for enabled state to be consistent.

2023-07-26 15:48 UTC, VanHoangTran commented on lib/src/chip/sbb_chip.dart
> +        horizontal: 12.0,
See my comment on line 105

2023-08-09 08:08 UTC, rawi-coding commented
@VanHoangTran I've updated the PR. Thanks for the review :-)

2023-08-09 17:16 UTC, VanHoangTran commented on lib/src/theme/styles/src/sbb_chip_style.dart
> +  final Color? unselectButtonColor;
Still missing label text color for both states ;-)

2023-08-09 17:16 UTC, VanHoangTran commented
Still missing label text color for both states ;-)
edit: Would actually be better to define textStyles instead of just text color :-)

2023-08-18 13:23 UTC, VanHoangTran approved these changes

2023-08-18 13:24 UTC, merged